/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebRouteRouteImport } from './routes/_web/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as WebIndexRouteImport } from './routes/_web/index'
import { Route as DashboardSettingIndexRouteImport } from './routes/_dashboard/setting/index'
import { Route as DashboardHomeIndexRouteImport } from './routes/_dashboard/home/index'
import { Route as DashboardChatIndexRouteImport } from './routes/_dashboard/chat/index'
import { Route as DashboardBillingIndexRouteImport } from './routes/_dashboard/billing/index'
import { Route as AuthSignUpIndexRouteImport } from './routes/_auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './routes/_auth/sign-in/index'

const WebRouteRoute = WebRouteRouteImport.update({
  id: '/_web',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WebIndexRoute = WebIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebRouteRoute,
} as any)
const DashboardSettingIndexRoute = DashboardSettingIndexRouteImport.update({
  id: '/setting/',
  path: '/setting/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHomeIndexRoute = DashboardHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardChatIndexRoute = DashboardChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingIndexRoute = DashboardBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WebIndexRoute
  '/sign-in/': typeof AuthSignInIndexRoute
  '/sign-up/': typeof AuthSignUpIndexRoute
  '/billing/': typeof DashboardBillingIndexRoute
  '/chat/': typeof DashboardChatIndexRoute
  '/home/': typeof DashboardHomeIndexRoute
  '/setting/': typeof DashboardSettingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WebIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
  '/billing': typeof DashboardBillingIndexRoute
  '/chat': typeof DashboardChatIndexRoute
  '/home': typeof DashboardHomeIndexRoute
  '/setting': typeof DashboardSettingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_web': typeof WebRouteRouteWithChildren
  '/_web/': typeof WebIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_dashboard/billing/': typeof DashboardBillingIndexRoute
  '/_dashboard/chat/': typeof DashboardChatIndexRoute
  '/_dashboard/home/': typeof DashboardHomeIndexRoute
  '/_dashboard/setting/': typeof DashboardSettingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in/'
    | '/sign-up/'
    | '/billing/'
    | '/chat/'
    | '/home/'
    | '/setting/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/billing'
    | '/chat'
    | '/home'
    | '/setting'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_web'
    | '/_web/'
    | '/_auth/sign-in/'
    | '/_auth/sign-up/'
    | '/_dashboard/billing/'
    | '/_dashboard/chat/'
    | '/_dashboard/home/'
    | '/_dashboard/setting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  WebRouteRoute: typeof WebRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_web': {
      id: '/_web'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web/': {
      id: '/_web/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebIndexRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_dashboard/setting/': {
      id: '/_dashboard/setting/'
      path: '/setting'
      fullPath: '/setting/'
      preLoaderRoute: typeof DashboardSettingIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/home/': {
      id: '/_dashboard/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof DashboardHomeIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/chat/': {
      id: '/_dashboard/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof DashboardChatIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/billing/': {
      id: '/_dashboard/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof DashboardBillingIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/sign-up/': {
      id: '/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardBillingIndexRoute: typeof DashboardBillingIndexRoute
  DashboardChatIndexRoute: typeof DashboardChatIndexRoute
  DashboardHomeIndexRoute: typeof DashboardHomeIndexRoute
  DashboardSettingIndexRoute: typeof DashboardSettingIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardBillingIndexRoute: DashboardBillingIndexRoute,
  DashboardChatIndexRoute: DashboardChatIndexRoute,
  DashboardHomeIndexRoute: DashboardHomeIndexRoute,
  DashboardSettingIndexRoute: DashboardSettingIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface WebRouteRouteChildren {
  WebIndexRoute: typeof WebIndexRoute
}

const WebRouteRouteChildren: WebRouteRouteChildren = {
  WebIndexRoute: WebIndexRoute,
}

const WebRouteRouteWithChildren = WebRouteRoute._addFileChildren(
  WebRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  WebRouteRoute: WebRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
